# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spec2llms < Formula
  desc "Generate llms.txt from OpenAPI/Swagger specifications"
  homepage "https://github.com/mdwitr0/spec2llms"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdwitr0/spec2llms/releases/download/v0.3.0/spec2llms_0.3.0_darwin_amd64.tar.gz"
      sha256 "95974ad288c5d404291bf0c422dfd21aa7627201bd4945527736ebb5456da826"

      def install
        bin.install "spec2llms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdwitr0/spec2llms/releases/download/v0.3.0/spec2llms_0.3.0_darwin_arm64.tar.gz"
      sha256 "2afecb4d6d086673a7d362fa4923f560c3ee3d30a7fd5919725e39b4be7c72da"

      def install
        bin.install "spec2llms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdwitr0/spec2llms/releases/download/v0.3.0/spec2llms_0.3.0_linux_amd64.tar.gz"
      sha256 "0f9304291ac07e760a9fd5a82e659293cb5fa9b72d5e9ef89901fda6350f1c5c"
      def install
        bin.install "spec2llms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdwitr0/spec2llms/releases/download/v0.3.0/spec2llms_0.3.0_linux_arm64.tar.gz"
      sha256 "2073b66fa2a711ed38cf0fa793f6d2ef4928362c0a9c8a381913a2aa427c91ea"
      def install
        bin.install "spec2llms"
      end
    end
  end

  test do
    system "#{bin}/spec2llms", "--version"
  end
end
