# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spec2llms < Formula
  desc "Generate llms.txt from OpenAPI/Swagger specifications"
  homepage "https://github.com/mdwitr0/spec2llms"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdwitr0/spec2llms/releases/download/v0.2.1/spec2llms_0.2.1_darwin_amd64.tar.gz"
      sha256 "646f3871f99c6116f7b69dc66b7e3a53b527b4b1d8264324d3b92654f3a86dba"

      def install
        bin.install "spec2llms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdwitr0/spec2llms/releases/download/v0.2.1/spec2llms_0.2.1_darwin_arm64.tar.gz"
      sha256 "3bac5d4407f1a31f2c77a419835a85cb965f103fa51504a010ed2e695a7f0bf5"

      def install
        bin.install "spec2llms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdwitr0/spec2llms/releases/download/v0.2.1/spec2llms_0.2.1_linux_amd64.tar.gz"
      sha256 "b24566b3991da634089f6f50eaa564a380381d0ee63fdee83d66e51d7b4a0300"
      def install
        bin.install "spec2llms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdwitr0/spec2llms/releases/download/v0.2.1/spec2llms_0.2.1_linux_arm64.tar.gz"
      sha256 "4a102e037de0ff1fec0234adfc801d9a4b3b0eaaebc6a64664dfff3aecdcd690"
      def install
        bin.install "spec2llms"
      end
    end
  end

  test do
    system "#{bin}/spec2llms", "--version"
  end
end
